# version: "4.0.0"

services:
  breeze:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_breeze
    container_name: breeze
    hostname: breeze
    ports:
      - "0.0.0.0:3000:80"
    volumes:
      - .:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=breeze_db
      - DB_PORT=3306
      - DB_DATABASE=breeze
      - DB_USERNAME=admin
      - DB_PASSWORD=A9x*UwARA5@
    depends_on:
      breeze_db:
        condition: service_healthy

  breeze_db:
    image: mysql:9.6
    container_name: breeze_db
    hostname: breeze_db
    ports:
        - "3305:3306" # Host:Container
    environment:
        - MYSQL_DATABASE=breeze
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=A9x*UwARA5@
        - MYSQL_ROOT_PASSWORD=Aa101985$
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db-data:
